language: cpp

install:
  - wget http://llvm.org/releases/5.0.0/clang+llvm-5.0.0-x86_64-linux-gnu-debian8.tar.xz
  - tar xvf clang+llvm-5.0.0-x86_64-linux-gnu-debian8.tar.xz
  - mv clang+llvm-5.0.0-x86_64-linux-gnu-debian8 llvm
  - ./utils/scripts/install_submodules.sh $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/llvm
  - printf "\n(set LLVM_CONFIG_BIN llvm)" >> configure.cmake

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j tiramisu

